name: Run OBWL Checker

on:
  schedule:
    - cron: '0 */1 * * *' # Будет запускаться автоматически каждые 2 часа
  workflow_dispatch:     # Позволит запускать скрипт руками кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run checker
        run: node checker.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add configs.txt
          git commit -m "Auto-update subscription configs" || exit 0
          git push
